### ISSUE TITLE
Add matching for :jpg 

### ISSUE THREAD

**Issue by webdeb** [Group4Layers/ex_image_info#1]
Hi, we are using your lib and checking for the correct type by parsing the ext name of an image and calling `seems?(binary, to_atom(ext))` 

For jpegs the ext is usually .jpg. So I thought maybe we could add a second matching:
`def seems?(binary, :jpg), do: JPEG.seems?(binary)` after the the original `:jpeg`.

What do you think?

**Comment by nozalr** [comment]
Hi, although the standard specifies "jpeg" and not "jpg" (this is something that comes from Windows), we decided to include it for you.
Check it out ;)

**Comment by webdeb** [comment]
Wow, thats just Awesome! Thank you very much 👍
