### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by axelson** [Group4Layers/ex_image_info#11]
Hi there! 👋 
Thank you for this library, I've been happily using it for a number of years now.

Is it possible to cut a new release? Mainly to avoid the charlists warning which looks like it's already fixed, although not yet released.

**Comment by rNoz** [comment]
Hi Jason! Sure thing, let me try to squeeze in some time this weekend.
P.S. I've enjoyed your talks. In fact, I picked up a couple of your tips recently ;).

**Comment by axelson** [comment]
Thank you for the kind words! I'm glad it was helpful to you!

**Comment by rNoz** [comment]
:) Just published.

**Comment by axelson** [comment]
Great, thank you so much!
