### ISSUE TITLE
ExImageInfo.info/1 and .info/2 don't match for :webp

### ISSUE THREAD

**Issue by Bscruz19** [Group4Layers/ex_image_info#2]
Hello, 
The `ExImageInfo.info/1` and `ExImageInfo.info/2` function returns `nil` in many cases for the webp format. When we use the `ExImageInfo.type` or  `ExImageInfo.seems?` functions it works fine.

Here has an example
```
url = "https://media3.giphy.com/media/jHCmUxSNgRjCOYDHiT/giphy.webp"
{:ok, %HTTPoison.Response{body: image}} = HTTPoison.get(url, []) 
ExImageInfo.type(image) # {"image/webp", "webpVP8"}
ExImageInfo.info(image) # nil
```

There is something that can be done, or the problem is with the picture itself?

**Comment by nozalr** [comment]
Hello, @Bscruz19 

Thanks for writing. Remember that you are encouraged to provide a PR solving the issue.
We'll try to solve as soon as possible.

Regards.

**Comment by nozalr** [comment]
Hi @Bscruz19. We worked on it. Also, new tests and fixtures are added (animated gif and webp). Please, try the library directly from the github repo and confirm that it works. Afterwards, we will publish the new hex.pm package.

**Comment by Bscruz19** [comment]
Hello @nozalr I tested here and is working perfectly!!!
Thank you for the correction, and congratulations for the library :D

**Comment by nozalr** [comment]
;) Package published in hex.pm.
