### ISSUE TITLE
PSD mime should be image/vnd.adobe.photoshop ?

### ISSUE THREAD

**Issue by michelson** [Group4Layers/ex_image_info#3]
Hello, thanks for this useful library.
Is possible to configure different mime types to respond to .PSD? I believe that the format should be `image/vnd.adobe.photoshop ` as documented in some mime types databases. 
Would you accept a pull request for this?

**Comment by nozalr** [comment]
Hey, @michelson! Thanks for your words.

Sure, your functionality will be welcomed. Be sure you prepare:
- tests
- check/review `credo`
- update the `excoveralls` coverage and total units tests results (README and docs badges)
- provide a simple explanation of the added functionality (in the PR, but if you find it necessary, also in the README and docs)

I will assist you when you do the PR.

Have a good day.

**Comment by michelson** [comment]
Thanks! I've ended up doing another package that does the [mime detection only](https://github.com/chaskiq/ex-marcel), thanks anyway for your willingness to help on this.

you can close this issue if you want, 
best
